name: CI

on:
  push:
    branches:
      - main # або інша ваша основна гілка
  pull_request:
    branches:
      - main # або інша ваша основна гілка

jobs:
  build:
    runs-on: ubuntu-latest # або інша система, яку ви використовуєте

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.7" # або інша версія Go, яку ви використовуєте

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x # Ви можете вказати бажану версію Task

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run Taskfile
        run: task all # Запускає задачу `all`, яка визначена у вашому Taskfile.yml
