name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Витягнути код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Встановити Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20" # Заміни на свою версію Go

      # 3. Встановити Task
      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | bash

      # 4. Оновити модулі та перевірити їх
      - name: Go mod tidy
        run: go mod tidy

      # 5. Виконати всі кроки з Taskfile
      - name: Run all tasks from Taskfile
        run: task all # Запускає всі завдання, визначені в Taskfile.yml

      # 6. Перевірити версію Go
      - name: Show Go Version
        run: go version
