name: CI

on:
  push:
    branches:
      - main # або інша ваша основна гілка
  pull_request:
    branches:
      - main # або інша ваша основна гілка

jobs:
  build:
    runs-on: ubuntu-latest # або інша система, яку ви використовуєте

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18" # або інша версія Go, яку ви використовуєте

      - name: Install go-task
        run: |
          curl -sSL https://github.com/go-task/task/releases/download/v3.9.0/task_linux_amd64.tar.gz | tar -xzv -C /usr/local/bin task
        # Завантажуємо та розпаковуємо go-task в /usr/local/bin

      - name: Run Taskfile
        run: task all # Запускає задачу `all`, яка визначена у вашому Taskfile.yml
