name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 2345:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-timeout=5s
          --health-retries=5
          --health-interval=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.7"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Wait for PostgreSQL to be ready
        run: |
          # Wait for PostgreSQL service to be ready
          until pg_isready -h localhost -p 2345 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Install uuid-ossp extension in PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=admin psql -h localhost -p 2345 -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

      - name: Run Taskfile (Tests)
        run: task all # Тут має бути ваш крок для запуску тестів
