name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.7"

      - name: Install Task
        run: |
          curl -sL https://taskfile.dev/install.sh | bash

      - name: Go mod tidy
        run: go mod tidy

      - name: Run all tasks from Taskfile
        run: task all

      - name: Show Go Version
        run: go version
